server:
  port: 8084

auth:
  enabled: false
  origin: "http://localhost:4200"
  jwt.key.set.uri: http://app-iam:8081/oauth2/jwks

spring:  
  datasource:
    url: jdbc:mysql://localhost:30308/RPInventoryDB
    username: root
    password: your_database_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

  cache:
      type: redis

  data:
    redis:
      host: redis-rp-inventory
      port: 6379
      password: your_redis_password_inventory
      timeout: 60000

businessentity-service:
  url: http://localhost:30082

logging:
  level:
    root: INFO
    org:
      springframework:
        security: INFO
    com.retailpulse: DEBUG
  file:
    name: logs/rp-inventory.log
