server:
  port: 8084

auth:
  enabled: true
  origin: "http://retailpulse.me:4200"
  jwt.key.set.uri: http://app-iam:8081/oauth2/jwks

spring:
  redis:
    host: localhost
    port: 6379

  datasource:
    url: jdbc:mysql://localhost:3307/RetailPulseDB
    username: root
    password: your_database_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true

businessentity-service:
  url: http://localhost:30082

cache:
    type: redis

data:
  redis:
    host: localhost
    port: 6379
    password: your_redis_password_inventory
    timeout: 60000

logging:
  level:
    root: INFO
    org:
      springframework:
        security: TRACE
    com.retailpulse: DEBUG
  file:
    name: logs/retailpulse.log
